// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWYJXO5AqvjhdvPcFL2KnDGEleNr3I30',
    appId: '1:475590953925:web:1da5b5982d66eaf1b819ac',
    messagingSenderId: '475590953925',
    projectId: 'logitrack-9aeed',
    authDomain: 'logitrack-9aeed.firebaseapp.com',
    storageBucket: 'logitrack-9aeed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMzqgulhzM0TOglVspet9Tl41V8CpYUY',
    appId: '1:475590953925:android:1a511defec703e88b819ac',
    messagingSenderId: '475590953925',
    projectId: 'logitrack-9aeed',
    storageBucket: 'logitrack-9aeed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFu63KjWMqtS-yP9WKUQYfc3NxsJC940',
    appId: '1:475590953925:ios:6172c6ac07538c2cb819ac',
    messagingSenderId: '475590953925',
    projectId: 'logitrack-9aeed',
    storageBucket: 'logitrack-9aeed.appspot.com',
    iosBundleId: 'com.example.logitrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFu63KjWMqtS-yP9WKUQYfc3NxsJC940',
    appId: '1:475590953925:ios:8d15d75a050ab7d5b819ac',
    messagingSenderId: '475590953925',
    projectId: 'logitrack-9aeed',
    storageBucket: 'logitrack-9aeed.appspot.com',
    iosBundleId: 'com.example.logitrack.RunnerTests',
  );
}
